# Import Numpy

In [1]:
import numpy as np

In [30]:
# Find if there is nan or not on given data
data = np.array([10,20,30,40, np.nan, 90,100])
data

array([ 10.,  20.,  30.,  40.,  nan,  90., 100.])

In [31]:
np.isnan(data)
np.mean(data)
# If there is Nan value in data and to convert it to number we use:
d = np.nan_to_num(data)
print(d)

[ 10.  20.  30.  40.   0.  90. 100.]


In [8]:
# Find the Mean, Median and Standard Deviation on given data
data = np.array([122,344,566,788,233,455])
data

array([122, 344, 566, 788, 233, 455])

In [7]:
print("Mean", np.mean(data))
print("Median", np.median(data))
print("Standard Deviation", np.std(data))

Mean 418.0
Median 399.5
Standard Deviation 218.8949519746858


In [38]:
# Create an array 
data = np.array([40, 50, 30, 60])
# Perform the where statement by creating a new variable and access the array on that variable.
result = np.where(data >= 50, 'Pass', 'Fail')
print(result)
# It will give you Boolean value on the given array
d = np.logical_and(data >= 40, data < 60)
print(d)
# It will give you the value from array which is > of <
d2 = data[np.logical_and(data > 50, data < 90)]
print(d2)

['Fail' 'Pass' 'Fail' 'Pass']
[ True  True False False]
[60]


In [39]:
# Sort the given Data
np.sort(data)

array([30, 40, 50, 60])

In [40]:
# Reshape the given data
data.reshape(2,2)

array([[40, 50],
       [30, 60]])

In [34]:
# Sliceing the given array of data
rp = np.array([0,1,2,3,4,5,6,7,8,9])
print(rp)
print(rp[1:6:2]) # start : stop : step
# Start from Index and stop at Index 3
print(rp[:4])
# Start from Index 3 and stop at the end of Index
print(rp[3:])
# Start from the Index and stop at end of the Index and slice with 2 step
print(rp[::2])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5]
[0 1 2 3]
[3 4 5 6 7 8 9]
[0 2 4 6 8]
